version: '3.8'

services:
  app:
    container_name: express-app
    build: .
    ports:
      - "5001:5001"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
